name: thesht
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^1.3.1
  flutter_map: ^0.0.1
  haversine: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/map/8/62/
    - assets/map/8/63/
    - assets/map/8/64/
    - assets/map/9/124/
    - assets/map/9/125/
    - assets/map/9/126/
    - assets/map/9/127/
    - assets/map/9/128/
    - assets/map/10/248/
    - assets/map/10/249/
    - assets/map/10/250/
    - assets/map/10/251/
    - assets/map/10/252/
    - assets/map/10/253/
    - assets/map/10/254/
    - assets/map/10/255/
    - assets/map/10/256/
    - assets/map/11/497/
    - assets/map/11/498/
    - assets/map/11/499/
    - assets/map/11/500/
    - assets/map/11/501/
    - assets/map/11/502/
    - assets/map/11/503/
    - assets/map/11/504/
    - assets/map/11/505/
    - assets/map/11/506/
    - assets/map/11/507/
    - assets/map/11/508/
    - assets/map/11/509/
    - assets/map/11/510/
    - assets/map/11/511/
    - assets/map/11/512/
    - assets/map/11/513/
    - assets/map/12/994/
    - assets/map/12/995/
    - assets/map/12/996/
    - assets/map/12/997/
    - assets/map/12/998/
    - assets/map/12/999/
    - assets/map/12/1000/
    - assets/map/12/1001/
    - assets/map/12/1002/
    - assets/map/12/1003/
    - assets/map/12/1004/
    - assets/map/12/1005/
    - assets/map/12/1006/
    - assets/map/12/1007/
    - assets/map/12/1008/
    - assets/map/12/1009/
    - assets/map/12/1000/
    - assets/map/12/1010/
    - assets/map/12/1011/
    - assets/map/12/1012/
    - assets/map/12/1013/
    - assets/map/12/1014/
    - assets/map/12/1015/
    - assets/map/12/1016/
    - assets/map/12/1017/
    - assets/map/12/1018/
    - assets/map/12/1019/
    - assets/map/12/1020/
    - assets/map/12/1021/
    - assets/map/12/1022/
    - assets/map/12/1023/
    - assets/map/12/1024/
    - assets/map/12/1025/
    - assets/map/12/1026/
    - assets/map/13/1989/
    - assets/map/13/1990/
    - assets/map/13/1991/
    - assets/map/13/1992/
    - assets/map/13/1993/
    - assets/map/13/1994/
    - assets/map/13/1995/
    - assets/map/13/1996/
    - assets/map/13/1997/
    - assets/map/13/1998/
    - assets/map/13/1999/
    - assets/map/13/2000/
    - assets/map/13/2001/
    - assets/map/13/2002/
    - assets/map/13/2003/
    - assets/map/13/2004/
    - assets/map/13/2005/
    - assets/map/13/2006/
    - assets/map/13/2007/
    - assets/map/13/2008/
    - assets/map/13/2009/
    - assets/map/13/2010/
    - assets/map/13/2011/
    - assets/map/13/2012/
    - assets/map/13/2013/
    - assets/map/13/2014/
    - assets/map/13/2015/
    - assets/map/13/2016/
    - assets/map/13/2017/
    - assets/map/13/2018/
    - assets/map/13/2019/
    - assets/map/13/2020/
    - assets/map/13/2021/
    - assets/map/13/2022/
    - assets/map/13/2023/
    - assets/map/13/2024/
    - assets/map/13/2025/
    - assets/map/13/2026/
    - assets/map/13/2027/
    - assets/map/13/2028/
    - assets/map/13/2029/
    - assets/map/13/2030/
    - assets/map/13/2031/
    - assets/map/13/2032/
    - assets/map/13/2033/
    - assets/map/13/2034/
    - assets/map/13/2035/
    - assets/map/13/2036/
    - assets/map/13/2037/
    - assets/map/13/2038/
    - assets/map/13/2039/
    - assets/map/13/2040/
    - assets/map/13/2041/
    - assets/map/13/2042/
    - assets/map/13/2043/
    - assets/map/13/2044/
    - assets/map/13/2045/
    - assets/map/13/2046/
    - assets/map/13/2047/
    - assets/map/13/2048/
    - assets/map/13/2049/
    - assets/map/13/2050/
    - assets/map/13/2051/
    - assets/map/13/2052/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
